kind: Deployment
apiVersion: apps/v1
metadata:
  name: mira-view
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mira-view
  template:
    metadata:
      labels:
        app: mira-view
    spec:
      containers:
      - name: mira-view
        image: ghcr.io/miraplanner/mira-view:master
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
        env:
          - name: REACT_APP_API_URL
            value: "http://localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: mira-view-nodeport
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30000
  selector:
    app: mira-view